### ISSUE TITLE
DDoS protection by Cloudflare

### ISSUE THREAD

**Issue by mbagiella** [Trackerz/Yggtorrent-DLM#9]
After installing the module. I'm unable to download any torrent. It seems blocked by DDoS protection :(

Please turn JavaScript on and reload the page.   
DDoS protection by Cloudflare  Ray ID: 6d6df8ec0c9f40f3

**Comment by Trackerz** [comment]
Hi i pushed a new version 1.3.4 and normally this is working fine now

**Comment by mbagiella** [comment]
Still not :(

Synology Get is downloading a Invalid torrent (html) and if I open it with a navigator it says :

Checking your browser before accessing www3.yggtorrent.re.

This process is automatic. Your browser will redirect to your requested content shortly.

Please allow up to 5 seconds…

File attached : .torrent replaced by .txt to be able to import

[736694.txt](https://github.com/Trackerz/Yggtorrent-DLM/files/7985791/736694.txt)

**Comment by Trackerz** [comment]
Did you have replaced the ygg.php file in the Web directory with the new one?

In the old file the user agent was missing for the curl request

**Comment by mbagiella** [comment]
Thank you, it works like a charm !
